# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '10.0'

target 'WarOfShogunateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WarOfShogunateDemo
  pod 'WarOfShogunate',:git=>'https://github.com/shendoublexiang/WarOfShogunate.git'
  
  target 'WarOfShogunateDemoTests' do
    inherit! :search_paths
  end

  target 'WarOfShogunateDemoUITests' do
    # Pods for testing
  end

end
